### ISSUE TITLE
Users can only level up now if messages start with the bot's prefix

### ISSUE THREAD

**Issue by Mini-Ware** [ahnaf-zamil/ayikobot#2]
The code that caused this bug:
![ayupbug.jpg](https://user-images.githubusercontent.com/67500556/110041709-83c55b80-7d7f-11eb-8c97-ff27c2039aea.jpg)

Example:
![aynoup.jpg](https://user-images.githubusercontent.com/67500556/110041720-8758e280-7d7f-11eb-96e8-81b4523523b9.jpg)

**Comment by ahnaf-zamil** [comment]
Ah I messed up the code, I meant `not event.message.content.startswith(prefix)`. Thanks for pointing it out!

I would like to make sure that commands don't count as messages, since leveling systems are made to make members interact with the server and send more messages there. So commands don't count as typical messages, even though they are normal messages to Discord

**Comment by ahnaf-zamil** [comment]
Fixed on latest commit
